---
title: My Jekyll
timezone: UTC
collections:
  coll1:
    title: Coll1
    output: true
  posts:
    title: Posts
    output: true
    mymeatadat:
    - alma: jsdfksdhfk
      körte: jhvksjhv
  uploads:
    title: Uploads
    output: true

theme: jekyll-theme-cayman